name: Build
 
on: [push]
 
jobs:
  build:
 
    runs-on: windows-latest
 
    steps:     
    - name: Setup MSBuild Path
      uses: microsoft/setup-msbuild@v1.0.3
       
    - name: Setup NuGet
      uses: nuget/setup-nuget@v1     

    - uses: actions/checkout@v1
      name: Checkout Code
     
    - name: Restore NuGet Packages
      run: nuget restore Wox.Plugin.Heimdall.sln
 
    - name: Build Wox Plugin
      run: msbuild Wox.Plugin.Heimdall.sln /p:Configuration=Release
    
    - name: Create Wox Plugin file
      uses: papeloto/action-zip@v1
      with:
        recursive: true
        files: Wox.Plugin.Heimdall\bin\Release\
        dest: Wox.Plugin.Heimdall.wox
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: published_wox
        path: ${{ github.workspace }}/Wox.Plugin.Heimdall.wox